services:
  api_node:
    container_name: api_node
    restart: unless-stopped
    build:
      context: ./
    ports:
      - "9000:9000"
    networks:
      - rent_room_network
    env_file:
      - ./.env

networks:
  rent_room_network:
    driver: bridge