services:
  api_node:
    container_name: api_node
    restart: unless-stopped
    build:
      context: ./
    ports:
      - "9000:9000"
    networks:
      - rent_room_network
    env_file:
      - ./.env


  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  rent_room_network:
    driver: bridge